name: weather_by_location
description: A new Flutter project.

publish_to: 'none'


environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  get_it: ^7.2.0
  http: ^1.1.0
  dio: ^5.1.1
  shared_preferences: ^2.0.18
  internet_connection_checker: ^1.0.0+1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  email_validator: ^2.1.17
  flutter_screenutil: ^5.8.4
  scale_button: ^2.1.2
  google_fonts: ^5.1.0
  flutter_smart_dialog: ^4.9.4
  flutter_svg: ^2.0.7
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
  - assets/
  - assets/images/
  - assets/icons/


